#!/usr/bin/env python3

"""
	This script compares the file-level metrics generated by Understand version 6 with the ones previously inserted in the database.

	@TODO
"""

from modules.common import log, DATABASE_CONFIG
from modules.database import Database
from modules.project import Project

####################################################################################################

project_list = Project.get_project_list_from_config()
id_to_project = {project.database_id: project for project in project_list}

with Database() as db:

	log.info('Comparing the metrics in the FILES_*, FUNCTIONS_*, and CLASSES_* tables.')

	database_name = DATABASE_CONFIG['database']
	success, error_code = db.execute_query(	'''
											SELECT TABLE_NAME, REGEXP_SUBSTR(TABLE_NAME, '[0-9]+') AS R_ID
											FROM INFORMATION_SCHEMA.TABLES
											WHERE (TABLE_NAME LIKE 'FILES_%' OR TABLE_NAME LIKE 'FUNCTIONS_%' OR TABLE_NAME LIKE 'CLASSES_%')
											AND TABLE_TYPE = 'BASE TABLE'
											AND TABLE_SCHEMA = %(database_name)s
											ORDER BY R_ID, TABLE_NAME;
											''',
											params={'database_name': database_name})

	if success:
		
		table_row_list = [row for row in db.cursor]
		log.info(f'Comparing a total of {len(table_row_list)} tables.')

		for table_row in table_row_list:

			table = table_row['TABLE_NAME']
			r_id = table_row['R_ID']
			project = id_to_project[r_id]

			log.info(f'Comparing the metrics in the table "{table}" ({r_id}) for the project "{project}".')

			for input_csv_path in project.find_output_csv_files('metrics'):

				metrics = pd.read_csv(input_csv_path, dtype=str)

				

	else:
		log.error(f'Failed to build the queries to change the primary key in the FILES_* tables with the error code {error_code}.')

log.info('Finished running.')
print('Finished running.')
