#!/usr/bin/env python3

"""
	This script inserts the data from any CSV files generated by "collect_vulnerabilities.py" into the VULNERABILITIES table in the database.
"""

import sys

import pandas as pd # type: ignore
from mysql.connector import errorcode as MySQLErrorCodes # type: ignore

from modules.common import log, deserialize_json_container
from modules.database import Database
from modules.project import Project

####################################################################################################

with Database() as db:

	project_list = Project.get_project_list_from_config()
	for project in project_list:
		
		for input_csv_path in project.find_output_csv_files('cve'):

			vulnerabilities = pd.read_csv(input_csv_path, dtype=str)
			for row in vulnerabilities.itertuples():

				cve = row.CVE

				vulnerability_types = deserialize_json_container(row[12], [])
				classification = ''.join(['>' + type + '<' for type in vulnerability_types]) if vulnerability_types else 'Undefined'

				cvss = row[5]
				cvss_rating = None
				
				if '9.0' <= cvss <= '10.0':
					cvss_rating = 'Critical'
				elif '7.0' <= cvss <= '8.9':
					cvss_rating = 'High'
				elif '4.0' <= cvss <= '6.9':
					cvss_rating = 'Medium'
				elif '0.1' <= cvss <= '3.9':
					cvss_rating = 'Low'
				elif cvss == '0.0':
					cvss_rating = 'None'
				else:
					log.warning(f'Could not map the CVSS "{cvss}" to a valid CVSS v3.0 rating.')

				bugzilla_urls = deserialize_json_container(row[15], [None])
				advisory_ids = deserialize_json_container(row[18], [None])

				"""
				for url in bugzilla_urls:

					db.execute_query(	'''
										INSERT IGNORE INTO VULNERABILITIES
										(
											V_ID, CVE, ID_ADVISORIES,
											V_CLASSIFICATION, V_IMPACT, VULNERABILITY_URL,
											PRODUCTS, Affects
										)
										VALUES
										(
											%(V_ID)s, %(CVE)s, %(ID_ADVISORIES)s,
											%(V_CLASSIFICATION)s, %(V_IMPACT)s, %(VULNERABILITY_URL)s,
											%(PRODUCTS)s, %(Affects)s
										);
										''',
										
										params = {
											'V_ID': None,
											'CVE': cve,
											'ID_ADVISORIES': None,
											'V_CLASSIFICATION': classification,
											'V_IMPACT': cvss_rating,
											'VULNERABILITY_URL': url,
											'PRODUCTS': None,
											'Affects': None
										}
									)
				"""
